server:
  port: 8888
  error:
    include-message: always
    include-binding-errors: always
  ssl:
    key-store: classpath:zhw.asia.jks
    key-store-password: ubuntu123??
    key-store-type: JKS
    enabled: true

spring:
  datasource:
    url: jdbc:postgresql://zhw.asia:5432/wechatapp
    username: root
    password: kkkzoz
    driver-class-name: org.postgresql.Driver
    paltform: POSTGRESQL
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: wechatapp
      port: 27017
      host: zhw.asia
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
  redis:
    host: zhw.asia
    port: 6379



mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto


